notifications:
  email: false

sudo: false

language: python

cache:
  pip: true

install:
  - travis_retry pip install -r requirements.txt

matrix:
  include:
    - env: TOXENV=isort-check
    - python: 3.6
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36

script:
  - tox -e $TOXENV

after_success:
  - coveralls
